#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  rootDomain: "SET_BY_TERRAFORM"
  basicAuthPassword: "SET_BY_TERRAFORM"
global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingress.adminDomain: "admin.{{.Values.projectValues.rootDomain}}"
      ingress.host: "admin.{{.Values.projectValues.rootDomain}}"
      ingress.rootDomain: "{{.Values.projectValues.rootDomain}}"
charts:
  # Local chart for development purposes
  basic-auth:
    namespace: routing
    repoURL: "https://github.com/iits-consulting/otc-infrastructure-charts-template.git" # Replace this with yours!
    targetRevision: "main"
    path: "local-charts/basic-auth"
    parameters:
      credentials.password: "{{.Values.projectValues.basicAuthPassword}}"
  iits-admin-dashboard:
    namespace: admin
    targetRevision: 1.7.1
    # values files needs to be inside this chart
    valueFile: "value-files/admin-dashboard/values.yaml"

  kafka:
    namespace: kafka
    targetRevision: 22.2.0-bitnamilegacy
    valueFile: "value-files/kafka/values.yaml"
    parameters:
      "kafka.replicaCount": "1"

#   Remote chart from public helm repo
#  bitnami-kafka:
#    namespace: bitnami-kafka # Which namespace should the service be deployed
#    repoURL: "https://charts.bitnami.com/bitnami" # Helm repo URL by default it takes the helm repo URL from line 11
#    targetRevision: 32.2.4
#    overrideChartName: kafka # You can override the chart name
#    disableAutoSync: false # If set to true the sync will not happen automatically, you need to do it manually over the UI
#    parameters:
#      "controller.replicaCount": "1"
#      "listeners.client.protocol": "PLAINTEXT"
  akhq:
    namespace: kafka
    repoURL: "https://akhq.io"
    targetRevision: 0.25.1
    valueFile: "value-files/akhq/values.yaml"
  # Override values with local values file
# Logging Stack: Grafana, Loki, und Promtail
  loki-stack:
    namespace: monitoring                 # Dedizierter Namespace für Monitoring/Logging
    repoURL: "https://grafana.github.io/helm-charts" # Offizielles Grafana Helm Repo
    targetRevision: 2.9.10                # Eine aktuelle, stabile Chart-Version. Prüfe ggf. auf neuere.
    # Der Chart-Name ist 'loki-stack', daher ist kein 'overrideChartName' nötig.
    # valueFile: "value-files/loki-stack/values.yaml" # Optional, aber SEHR empfohlen für die Konfiguration!
    parameters:
      # Hier ein paar grundlegende Overrides.
      # Richtig sauber wird's mit der valueFile oben.
      grafana:
        enabled: true                     # Wir wollen Grafana ja haben
      prometheus:
        enabled: false                    # Wichtig: Deaktivieren, wenn du Prometheus separat deployen willst
      loki:
        persistence:
          enabled: true
          storageClassName: "cs-disk-ssd-retain-encrypted" # WICHTIG: Ersetze das mit deiner StorageClass!
      promtail:
        enabled: true                     # Der Agent, der die Logs sammelt
